kind = "web"
previewPath = "/"
title = "Kartigo"
version = "1.0.0"
id = "artifacts/kartigo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24899

[services.development]
run = "pnpm --filter @workspace/kartigo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kartigo", "run", "build" ]
publicDir = "artifacts/kartigo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24899"
BASE_PATH = "/"
